"""Initial tables

Revision ID: db1bdebbbfbf
Revises: c74a68956f32
Create Date: 2026-08-06 08:26:43.881145

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'db1bdebbbfbf'
down_revision: str | Sequence[str] | None = 'c74a68956f32'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
